SELECT ?reference ?subjOfProp ?objOfProp ?isA ?propertyDomain ?propertyRange WHERE { <$uri> <http://www.monnet-project.eu/lemon#sense> ?s . ?s <http://www.monnet-project.eu/lemon#reference> ?reference . OPTIONAL { ?s <http://www.monnet-project.eu/lemon#subjOfProp> ?subjOfProp . } OPTIONAL { ?s <http://www.monnet-project.eu/lemon#objOfProp> ?objOfProp . } OPTIONAL { ?s <http://www.monnet-project.eu/lemon#isA> ?isA . } OPTIONAL { ?s <http://www.monnet-project.eu/lemon#propertyDomain> ?propertyDomain . } OPTIONAL { ?s <http://www.monnet-project.eu/lemon#propertyRange> ?propertyRange . } }
