SELECT ?blank ?frame ?subject ?directObject ?indirectObject ?prepositionalObject ?synArg WHERE {  <$uri> <http://www.monnet-project.eu/lemon#synBehavior> ?blank .
 ?blank a ?frame .  OPTIONAL {   { ?blank <http://www.lexinfo.net/ontology/2.0/lexinfo#subject> ?subject . }   UNION  { ?blank <http://www.isocat.org/datcat/DC-2261> ?subject . }  }  OPTIONAL {   { ?blank <http://www.lexinfo.net/ontology/2.0/lexinfo#directObject> ?directObject . }   UNION  { ?blank <http://www.isocat.org/datcat/DC-2263> ?directObject . }  }  OPTIONAL {   { ?blank <http://www.lexinfo.net/ontology/2.0/lexinfo#indirectObject> ?indirectObject . }   UNION  { ?blank <http://www.isocat.org/datcat/DC-1310> ?indirectObject . }  }  OPTIONAL {   { ?blank <http://www.lexinfo.net/ontology/2.0/lexinfo#prepositionalObject> ?prepositionalObject . }   UNION  { ?blank <http://www.isocat.org/datcat/DC-4638> ?prepositionalObject . }  }  OPTIONAL { ?blank <http://www.monnet-project.eu/lemon#synArg> ?synArg . } }
